
export const CATEGORY_OPTIONS = [

        {value: null, label: "All Categories"},
        {value: "clothing", label: "Clothing, Shoes & Accessories"},
        {value: "collectibles", label: "Collectibles"},
        {value: "tvAndMovies", label: "Movies & TV"},
        {value: "toys", label: "Toys & Hobbies"},
        {value: "videoGames", label: "Video Games & Consoles"},
        {value: "computer", label: "Computers/Tablets & Networking"},
        {value: "jewelry", label: "Jewelry & Watches"},
        {value: "books", label: "Books & Magazines"},
        {value: "crafts", label: "Crafts"},
        {value: "sportingGoods", label: "Sporting Goods"},
        {value: "homeGarden", label: "Home & Garden"},
        {value: "art", label: "Art"},
        //{value: "Pottery & Glass", label: "Pottery & Glass"},
        //{value: "Home Décor", label: "Home Décor"},
        //{value: "Business & Industrial", label: "Business & Industrial"},
        //{value: "eBay Motors", label: "eBay Motors"},
        //{value: "Music Memorabilia", label: "Music Memorabilia"},
]

export const SUB_CATEGORY_OPTIONS = {
        "Collectibles": [{ value: null, label: "All Collectibles"},
                        { value: "Trading Card Singles", label: "Trading Card Singles"},
                        { value: "Trading Card Lots", label: "Trading Card Lots"},
                        { value: "Comics", label: "Comics"},
                        { value: "Collectible Figures & Bobbleheads", label: "Collectible Figures & Bobbleheads"},
                        { value: "Coca-Cola", label: "Coca-Cola"},
                        { value: "Disney", label: "Disney"},
                        { value: "Postcards", label: "Postcards"},
                        { value: "Stamps", label: "Stamps"},
                        { value: "Sports Mem, Cards & Fan Shop", label: "Sports Mem, Cards & Fan Shop"}, 
                        { value: "Antique (Pre-1900)", label: 'Antique (Pre-1900)'},
                        { value: "Civil War (1861-65)", label: "Civil War (1861-65)"},
                        { value: "Advertising", label: "Advertising"},
                        { value: "Records", label: "Records"},
                        { value: "Star Wars Collectibles", label: "Star Wars Collectibles"},
                        { value: "Patches, Pins & Buttons", label: "Patches, Pins & Buttons"}],
        "Clothing, Shoes & Accessories": [{value: null, label: "All Clothing"},       
                                         {value: "Women's Clothing", label: "Womens's Clothing"},
                                         {value: "Women's Bags & Handbags", label: "Women's Bags & Handbags"},
                                         {value: "Girls", label: "Girls"}, 
                                         {value: "Boys", label: "Boys"},
                                         {value: "Men", label: "Men"},
                                         {value:"Men's Clothing", label: "Men's Clothing"},
                                        {value: "Baby & Toddler Clothing", label:"Baby & Toddler Clothing"}],

        "Books & Magazines": [{value: null, label: "All Books & Magazines"},
                              {value: "Textbooks", label: "Textbooks"},
                              {value: "Magazines", label: "Magazines"},
                              {value: "Books", label: "Books"},
                              {value: "Antiquarian & Collectible", label: "Antiquarian & Collectible"},
                              {value: "Audiobooks", label: "Audiobooks"},
                              {value: "Study Guides & Test Prep", label: "Study Guides & Test Prep"},
                              {value: "Dictionaries & Reference", label: "Dictionaries & Reference"}],

        "Video Games & Consoles": [{value: null, label: "All Video Games & Consoles"},
                                    {value: "Video Game Consoles", label: "Video Game Consoles"},
                                    {value: "Video Games", label: "Video Games"},
                                    {value: "Controllers & Attachments", label: "Controllers & Attachments"},
                                    {value: "Video Game Merchandise", label: "Video Game Merchandise"},
                                    {value: "Headsets", label: "Headsets"},
                                    {value: "Original Game Cases & Boxes", label: "Original Game Cases & Boxes"}],

        "Jewelry & Watches": [{value: null, label: "All Jewelery & Watches"},
                                {value: "Rings", label: "Rings"},
                                {value: "Watches", label: "Watches"},
                                {value: "Earrings", label: "Earrings"},
                                {value: "Bracelets & Charms", label: "Bracelets & Charms"}
        ],

        "Movies & TV": [{value: null, label: "All Movies & TV"},
                        { value: "DVDs & Blu-ray Discs", label: "DVDs & Blu-ray Discs" },
                        { value: "VHS Tapes", label: "VHS Tapes"},
                        { value: "Film Stock", label: "Film Stock"},
                        { value: "Other Formats", label: "Other Formats"}
        ],

        "Toys & Hobbies": [{value: null, label: "All Toys & Hobbies"},
                         {value: "Action Figures", label: "Action Figures"},
                         {value: "Fisher Price", label: "Fisher Price"},
                         {value: "Disney", label: "Disney"},
                         {value: "LEGO (R) Complete Sets & Packs", label: "LEGO (R) Complete Sets & Packs"},
                         {value: "LEGO (R) Building Toys", label: "LEGO (R) Building Toys"},
                         {value: "LEGO (R) Bricks, Pieces & Parts", label: "LEGO (R) Bricks, Pieces & Parts"},
                         {value: "Puzzles", label: "Puzzles"},
                         {value: "Electronic Games", label: "Electronic Games"},
                         {value: "Models & Kits", label: "Models & Kits"},
                         {value: "Cars: Racing, NASCAR", label: "Cars: Racing, NASCAR"},
                         {value: "Star Wars", label: "Star Wars"}
        ],

        "Crafts": [{value: null, label: "All Crafts"},
                   {value: "Sewing", label: "Sewing"},
                   {value: "Quilting", label: "Quilting"},
                   {value: "Embroidery & Cross Stitch", label: "Embroidery & Cross Stitch"},
                   {value: "Kids' Crafts", label: "Kids' Crafts"},
                   {value: "Craft Kits", label: "Craft Kits"}
        ],

        "Sporting Goods": [{value: null, label: "All Sporting Goods"},
                           {value: "Football", label: "Football"},
                           {value: "Basketball", label: "Basketball"},
                           {value: "Baseball", label: "Baseball"},
                           {value: "Golf", label: "Golf"},
                           {value: "Soccer", label: "Soccer"},
                           {value: "Tennis", label: "Tennis"},
                           {value: "Cycling", label: "Cycling"},
                           {value: "Skateboarding & Longboarding", label: "Skateboarding & Longboarding"},
                           {value: "Fishing", label: "Fishing"},
                           {value: "Hunting", label: "Hunting"},
                           {value: "Ice Skating", label: 'Ice Skating'}
        ],

        "Computers/Tablets & Networking": [{value: null, label: "All Computers/Tablets & Networking"},
                                           {value: "Desktops & All-In-Ones", label: "Desktops & All-In-Ones"},
                                           {value: "PC Laptops & Netbooks", label: "PC Laptops & Netbooks"},
                                           {value: "Tablets & eBook Readers", label: "Tablets & eBook Readers"},
                                           {value: "Apple Laptops", label: "Apple Laptops"},
                                           {value: "Apple Desktops & All-In-Ones", label: "Apple Desktops & All-In-Ones"},
                                           {value: "Monitors", label: "Monitors"},
                                           {value: "Printers", label: "Printers"},
                                           {value: "Laptop Replacement Parts", label: "Laptop Replacement Parts"},
                                           {value: "Graphics/Video Cards", label: "Graphics/Video Cards"},
                                           {value: "Enterprise Networking, Servers", label: "Enterprise Networking, Servers"},                    
        ],

        "Home & Garden": [{value: null, label: "All Home & Garden"},
                          {value: "Candles & Home Fragrance", label: "Candles & Home Fragrance"},
                          {value: "Glassware & Drinkware", label: "Glassware & Drinkware"},
                          {value: "Flatware, Knives & Cutlery", label: "Flatware, Knives & Cutlery"},
                          {value: "Dinnerware & Serveware", label: "Dinnerware & Serveware"},
                          {value: "Kitchen Tools & Gadgets", label: "Kitchen Tools & Gadgets"},
                          {value: "Coffee, Tea & Espresso Makers", label: "Coffee, Tea & Espresso Makers"},
                          {value: "Bakeware", label: "Bakeware"},
                          {value: "Cookware", label: "Cookware"},
                          {value: "Grills & Griddles", label: "Grills & Griddles"},
                          {value: "Wall Décor", label: "Wall Décor"},
                          {value: "Furniture", label: "Furniture"},
                          {value: "Bedding", label: "Bedding"},
                          {value: "Kitchen, Dining & Bar", label: "Kitchen, Dining & Bar"},
                          {value: "Small Kitchen Appliances", label: "Small Kitchen Appliances"},
                          {value: "Patio & Garden Furniture", label: "Patio & Garden Furniture"},
                          {value: "Garden Hand Tools & Equipment", label: "Garden Hand Tools & Equipment"},
                          {value: "Plants, Seeds & Bulbs", label: "Plants, Seeds & Bulbs"},
                          {value: "Plant Care, Soil & Accessories", label: "Plant Care, Soil & Accessories"},
                          {value: "Herbs, Spices & Seasonings", label: "Herbs, Spices & Seasonings"},
        ],

        "Art": [{value: null, label: "All Art"},
                {value: "Art Prints", label: "Art Prints"},
                {value: "Paintings", label: "Paintings"},
                {value: "Art Sculptures", label: "Art Sculptures"},
                {value: "Art Posters", label: "Art Posters"},
                {value: "Mixed Media Art & Collage Art", label: "Mixed Media Art & Collage Art"},
                {value: "Other Art", label: "Other Art"},
                {value: "Art Photographs", label: "Art Photographs"},
                {value: "Art Drawings", label: "Art Drawings"},
                {value: "Art NFTs", label: "Art NFTs"},
                {value: "Textile Art & Fiber Art", label: "Textile Art & Fiber Art"}
        ]     
}