export const GET_ITEMS_REQUEST = 'GET_ITEMS_REQUEST'
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS'
export const GET_ITEMS_ERROR = 'GET_ITEMS_ERROR'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const GET_CHARITIES_REQUEST = 'GET_CHARITIES_REQUEST'
export const GET_CHARITIES_SUCCESS = 'GET_CHARITIES_SUCCESS'
export const GET_CHARITIES_ERROR = 'GET_CHARITIES_ERROR'

export const DELETE_CHARITY_REQUEST = 'DELETE_CHARITY_REQUEST'
export const DELETE_CHARITY_SUCCESS = 'DELETE_CHARITY_SUCCESS'
export const DELETE_CHARITY_ERROR = 'DELETE_CHARITY_ERROR'

export const ADD_CHARITY_REQUEST = 'ADD_CHARITY_REQUEST'
export const ADD_CHARITY_SUCCESS = 'ADD_CHARITY_SUCCESS'
export const ADD_CHARITY_ERROR = 'ADD_CHARITY_ERROR'

export const GET_FAVORITES_REQUEST = 'GET_FAVORITES_REQUEST'
export const GET_FAVORITES_SUCCESS = 'GET_FAVORITES_SUCCESS'
export const GET_FAVORITES_ERROR = 'GET_FAVORITES_ERROR'
export const ADD_FAVORITE_REQUEST = 'ADD_FAVORITE_REQUEST'
export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE_SUCCESS'
export const ADD_FAVORITE_ERROR = 'ADD_FAVORITE_ERROR'
export const REMOVE_FAVORITE_REQUEST = 'REMOVE_FAVORITE_REQUEST'
export const REMOVE_FAVORITE_SUCCESS = 'REMOVE_FAVORITE_SUCCESS'
export const REMOVE_FAVORITE_ERROR = 'REMOVE_FAVORITE_ERROR'